//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.28 at 10:31:24 AM CST 
//


package com.pplive.bip.scheduler.oozie.workflow2;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ACTION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACTION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="map-reduce" type="{uri:oozie:workflow:0.1}MAP-REDUCE"/>
 *           &lt;element name="pig" type="{uri:oozie:workflow:0.1}PIG"/>
 *           &lt;element name="ssh" type="{uri:oozie:workflow:0.1}SSH"/>
 *           &lt;element name="sub-workflow" type="{uri:oozie:workflow:0.1}SUB-WORKFLOW"/>
 *           &lt;element name="fs" type="{uri:oozie:workflow:0.1}FS"/>
 *           &lt;element name="http" type="{uri:oozie:workflow:0.1}HTTP"/>
 *           &lt;element name="email" type="{uri:oozie:workflow:0.1}EMAIL"/>
 *           &lt;element name="java" type="{uri:oozie:workflow:0.1}JAVA"/>
 *           &lt;any namespace='##other'/>
 *         &lt;/choice>
 *         &lt;element name="ok" type="{uri:oozie:workflow:0.1}ACTION_TRANSITION"/>
 *         &lt;element name="error" type="{uri:oozie:workflow:0.1}ACTION_TRANSITION"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{uri:oozie:workflow:0.1}IDENTIFIER" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACTION", propOrder = {
    "mapReduce",
    "pig",
    "ssh",
    "shell",
    "subWorkflow",
    "fs",
    "http",
    "email",
    "java",
    "hive",
    "any",
    "ok",
    "error"
})
public class Action {

    @XmlElement(name = "map-reduce")
    protected MapReduceNode mapReduce;
    protected PigNode pig;
    protected SSHNode ssh;
    @XmlElement(namespace = "uri:oozie:shell-action:0.1")
    protected ShellNode shell;
    @XmlElement(name = "sub-workflow")
    protected SubWorkflow subWorkflow;
    protected FSNode fs;
    protected HTTPNode http;
    protected EmailNode email;
    protected JavaNode java;
    @XmlElement()
//	protected HiveNode hive;
    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlElement(required = true)
    protected ActionTransition ok;
    @XmlElement(required = true)
    protected ActionTransition error;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    

    /**
     * Gets the value of the mapReduce property.
     * 
     * @return
     *     possible object is
     *     {@link MapReduceNode }
     *     
     */
    public MapReduceNode getMapReduce() {
        return mapReduce;
    }

    /**
     * Sets the value of the mapReduce property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapReduceNode }
     *     
     */
    public void setMapReduce(MapReduceNode value) {
        this.mapReduce = value;
    }

    /**
     * Gets the value of the pig property.
     * 
     * @return
     *     possible object is
     *     {@link PigNode }
     *     
     */
    public PigNode getPig() {
        return pig;
    }

    /**
     * Sets the value of the pig property.
     * 
     * @param value
     *     allowed object is
     *     {@link PigNode }
     *     
     */
    public void setPig(PigNode value) {
        this.pig = value;
    }

    /**
     * Gets the value of the ssh property.
     * 
     * @return
     *     possible object is
     *     {@link SSHNode }
     *     
     */
    public SSHNode getSsh() {
        return ssh;
    }

    /**
     * Sets the value of the ssh property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSHNode }
     *     
     */
    public void setSsh(SSHNode value) {
        this.ssh = value;
    }

    /**
     * Gets the value of the subWorkflow property.
     * 
     * @return
     *     possible object is
     *     {@link SubWorkflow }
     *     
     */
    public SubWorkflow getSubWorkflow() {
        return subWorkflow;
    }

    /**
     * Sets the value of the subWorkflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubWorkflow }
     *     
     */
    public void setSubWorkflow(SubWorkflow value) {
        this.subWorkflow = value;
    }

    /**
     * Gets the value of the fs property.
     * 
     * @return
     *     possible object is
     *     {@link FSNode }
     *     
     */
    public FSNode getFs() {
        return fs;
    }

    /**
     * Sets the value of the fs property.
     * 
     * @param value
     *     allowed object is
     *     {@link FSNode }
     *     
     */
    public void setFs(FSNode value) {
        this.fs = value;
    }

    /**
     * Gets the value of the http property.
     * 
     * @return
     *     possible object is
     *     {@link HTTPNode }
     *     
     */
    public HTTPNode getHttp() {
        return http;
    }

    /**
     * Sets the value of the http property.
     * 
     * @param value
     *     allowed object is
     *     {@link HTTPNode }
     *     
     */
    public void setHttp(HTTPNode value) {
        this.http = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link EmailNode }
     *     
     */
    public EmailNode getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailNode }
     *     
     */
    public void setEmail(EmailNode value) {
        this.email = value;
    }
    
    /**
     * Gets the value of the hive property.
     * 
     * @return
     *     possible object is
     *     {@link HiveNode }
     *     
     */
//    public HiveNode getHive() {
//		return hive;
//	}
//
//    /**
//     * Sets the value of the hive property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link HiveNode }
//     *
//     */
//	public void setHive(HiveNode hive) {
//		this.hive = hive;
//	}
	
    /**
     * Gets the value of the java property.
     * 
     * @return
     *     possible object is
     *     {@link JavaNode }
     *     
     */
    public JavaNode getJava() {
        return java;
    }

    /**
     * Sets the value of the java property.
     * 
     * @param value
     *     allowed object is
     *     {@link JavaNode }
     *     
     */
    public void setJava(JavaNode value) {
        this.java = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the ok property.
     * 
     * @return
     *     possible object is
     *     {@link ActionTransition }
     *     
     */
    public ActionTransition getOk() {
        return ok;
    }

    /**
     * Sets the value of the ok property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionTransition }
     *     
     */
    public void setOk(ActionTransition value) {
        this.ok = value;
    }

    /**
     * shortcut for set ok
     */
    public void setOkTo(String name) {
    	ActionTransition transit = new ActionTransition();
    	transit.setTo(name);
		this.setOk(transit);
    }
    
    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ActionTransition }
     *     
     */
    public ActionTransition getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionTransition }
     *     
     */
    public void setError(ActionTransition value) {
        this.error = value;
    }
    
    /**
     * shortcut for set error
     */
    public void setErrorTo(String name) {
    	ActionTransition transit = new ActionTransition();
    	transit.setTo(name);
		this.setError(transit);
    }
    
    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

	public ShellNode getShell() {
		return shell;
	}

	public void setShell(ShellNode shell) {
		this.shell = shell;
	}
    
}
