//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.28 at 10:31:24 AM CST 
//


package com.pplive.bip.scheduler.oozie.workflow2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HTTP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HTTP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="http-url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="post" type="{uri:oozie:workflow:0.1}HTTP-POST" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="wait" type="{uri:oozie:workflow:0.1}FLAG"/>
 *           &lt;element name="continue" type="{uri:oozie:workflow:0.1}FLAG"/>
 *         &lt;/choice>
 *         &lt;element name="capture-output" type="{uri:oozie:workflow:0.1}FLAG"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HTTP", propOrder = {
    "httpUrl",
    "post",
    "wait",
    "_continue",
    "captureOutput"
})
public class HTTPNode {

    @XmlElement(name = "http-url", required = true)
    protected String httpUrl;
    protected HTTPPost post;
    protected StateFlag wait;
    @XmlElement(name = "continue")
    protected StateFlag _continue;
    @XmlElement(name = "capture-output", required = true)
    protected StateFlag captureOutput;

    /**
     * Gets the value of the httpUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHttpUrl() {
        return httpUrl;
    }

    /**
     * Sets the value of the httpUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHttpUrl(String value) {
        this.httpUrl = value;
    }

    /**
     * Gets the value of the post property.
     * 
     * @return
     *     possible object is
     *     {@link HTTPPost }
     *     
     */
    public HTTPPost getPost() {
        return post;
    }

    /**
     * Sets the value of the post property.
     * 
     * @param value
     *     allowed object is
     *     {@link HTTPPost }
     *     
     */
    public void setPost(HTTPPost value) {
        this.post = value;
    }

    /**
     * Gets the value of the wait property.
     * 
     * @return
     *     possible object is
     *     {@link StateFlag }
     *     
     */
    public StateFlag getWait() {
        return wait;
    }

    /**
     * Sets the value of the wait property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateFlag }
     *     
     */
    public void setWait(StateFlag value) {
        this.wait = value;
    }

    /**
     * Gets the value of the continue property.
     * 
     * @return
     *     possible object is
     *     {@link StateFlag }
     *     
     */
    public StateFlag getContinue() {
        return _continue;
    }

    /**
     * Sets the value of the continue property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateFlag }
     *     
     */
    public void setContinue(StateFlag value) {
        this._continue = value;
    }

    /**
     * Gets the value of the captureOutput property.
     * 
     * @return
     *     possible object is
     *     {@link StateFlag }
     *     
     */
    public StateFlag getCaptureOutput() {
        return captureOutput;
    }

    /**
     * Sets the value of the captureOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateFlag }
     *     
     */
    public void setCaptureOutput(StateFlag value) {
        this.captureOutput = value;
    }

}
