//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.28 at 10:31:24 AM CST 
//


package com.pplive.bip.scheduler.oozie.workflow2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for MAP-REDUCE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MAP-REDUCE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="job-tracker" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name-node" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prepare" type="{uri:oozie:workflow:0.1}PREPARE" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="streaming" type="{uri:oozie:workflow:0.1}STREAMING" minOccurs="0"/>
 *           &lt;element name="pipes" type="{uri:oozie:workflow:0.1}PIPES" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="job-xml" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="configuration" type="{uri:oozie:workflow:0.1}CONFIGURATION" minOccurs="0"/>
 *         &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="archive" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MAP-REDUCE", propOrder = {
    "jobTracker",
    "nameNode",
    "prepare",
    "streaming",
    "pipes",
    "jobXml",
    "configuration",
    "file",
    "archive"
})
public class MapReduceNode {

    @XmlElement(name = "job-tracker", required = true)
    protected String jobTracker;
    @XmlElement(name = "name-node", required = true)
    protected String nameNode;
    protected PrepareNode prepare;
    protected StreamingNode streaming;
    protected PipesNode pipes;
    @XmlElement(name = "job-xml")
    protected String jobXml;
    protected ConfigurationNode configuration;
    protected List<String> file;
    protected List<String> archive;

    /**
     * Gets the value of the jobTracker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobTracker() {
        return jobTracker;
    }

    /**
     * Sets the value of the jobTracker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobTracker(String value) {
        this.jobTracker = value;
    }

    /**
     * Gets the value of the nameNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameNode() {
        return nameNode;
    }

    /**
     * Sets the value of the nameNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameNode(String value) {
        this.nameNode = value;
    }

    /**
     * Gets the value of the prepare property.
     * 
     * @return
     *     possible object is
     *     {@link PrepareNode }
     *     
     */
    public PrepareNode getPrepare() {
        return prepare;
    }

    /**
     * Sets the value of the prepare property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrepareNode }
     *     
     */
    public void setPrepare(PrepareNode value) {
        this.prepare = value;
    }

    /**
     * Gets the value of the streaming property.
     * 
     * @return
     *     possible object is
     *     {@link StreamingNode }
     *     
     */
    public StreamingNode getStreaming() {
        return streaming;
    }

    /**
     * Sets the value of the streaming property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamingNode }
     *     
     */
    public void setStreaming(StreamingNode value) {
        this.streaming = value;
    }

    /**
     * Gets the value of the pipes property.
     * 
     * @return
     *     possible object is
     *     {@link PipesNode }
     *     
     */
    public PipesNode getPipes() {
        return pipes;
    }

    /**
     * Sets the value of the pipes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PipesNode }
     *     
     */
    public void setPipes(PipesNode value) {
        this.pipes = value;
    }

    /**
     * Gets the value of the jobXml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobXml() {
        return jobXml;
    }

    /**
     * Sets the value of the jobXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobXml(String value) {
        this.jobXml = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationNode }
     *     
     */
    public ConfigurationNode getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationNode }
     *     
     */
    public void setConfiguration(ConfigurationNode value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the file property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFile() {
        if (file == null) {
            file = new ArrayList<String>();
        }
        return this.file;
    }

    /**
     * Gets the value of the archive property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the archive property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchive().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getArchive() {
        if (archive == null) {
            archive = new ArrayList<String>();
        }
        return this.archive;
    }

}
