//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.28 at 10:31:24 AM CST 
//
//copy from raw bip

@javax.xml.bind.annotation.XmlSchema(namespace = "uri:oozie:workflow:0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@Deprecated
package com.pplive.bip.scheduler.oozie.workflow2;
